version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_test:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock  
  spark-master:     
    image: cluster-apache-spark:3.0.2     
    ports:       
    - "9090:8080"      
    - "7077:7077"     
    volumes:        
    - ./apps:/opt/spark-apps        
    - ./data:/opt/spark-data     
    environment:       
    - SPARK_LOCAL_IP=spark-master       
    - SPARK_WORKLOAD=master   
  spark-worker-a:     
    image: cluster-apache-spark:3.0.2     
    ports:       
    - "9091:8080"       
    - "7000:7000"     
    depends_on:       
    - spark-master    
    environment:       
    - SPARK_MASTER=spark://spark-master:7077       
    - SPARK_WORKER_CORES=1       
    - SPARK_WORKER_MEMORY=1G       
    - SPARK_DRIVER_MEMORY=1G       
    - SPARK_EXECUTOR_MEMORY=1G       
    - SPARK_WORKLOAD=worker       
    - SPARK_LOCAL_IP=spark-worker-a     
    volumes:        
    - ./apps:/opt/spark-apps        
    - ./data:/opt/spark-data   
  spark-worker-b:     
    image: cluster-apache-spark:3.0.2     
    ports:       
    - "9092:8080"       
    - "7001:7000"     
    depends_on:       
    - spark-master     
    environment:       
    - SPARK_MASTER=spark://spark-master:7077       
    - SPARK_WORKER_CORES=1       
    - SPARK_WORKER_MEMORY=1G       
    - SPARK_DRIVER_MEMORY=1G       
    - SPARK_EXECUTOR_MEMORY=1G       
    - SPARK_WORKLOAD=worker       
    - SPARK_LOCAL_IP=spark-worker-b     
    volumes:         
    - ./apps:/opt/spark-apps         
    - ./data:/opt/spark-data   
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db